# Site settings
title: syaning
baseurl: ""
url: "http://syaning.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
google_analytics: UA-56203680-1
disqus_shortname: 
